@urlbase=http://localhost:3000
@urlhealth={{urlbase}}/health
@urlUser={{urlbase}}/users

### Health Check
GET {{urlhealth}}

### Login

###
POST {{urlUser}}
Content-Type: application/json

{

    "nombre": "Erik",
    "email": "erik@gmail.com",
    "password": "1234",
    "rol": "alumno"
}